//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_platformer : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Vector2 Move
        {
            get
            {
                return SteamVR_Actions.platformer_Move;
            }
        }
        
        public virtual SteamVR_Action_Boolean Jump
        {
            get
            {
                return SteamVR_Actions.platformer_Jump;
            }
        }
        
        public virtual SteamVR_Action_Pose Pose
        {
            get
            {
                return SteamVR_Actions.platformer_Pose;
            }
        }
        
        public virtual SteamVR_Action_Boolean Select
        {
            get
            {
                return SteamVR_Actions.platformer_Select;
            }
        }
        
        public virtual SteamVR_Action_Boolean Tube
        {
            get
            {
                return SteamVR_Actions.platformer_Tube;
            }
        }
        
        public virtual SteamVR_Action_Boolean Shoot
        {
            get
            {
                return SteamVR_Actions.platformer_Shoot;
            }
        }
        
        public virtual SteamVR_Action_Boolean Menu
        {
            get
            {
                return SteamVR_Actions.platformer_Menu;
            }
        }
        
        public virtual SteamVR_Action_Boolean Accept
        {
            get
            {
                return SteamVR_Actions.platformer_Accept;
            }
        }
    }
}
